# Generated by Django 5.0.2 on 2024-02-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartu',
            name='contity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
