# Generated by Django 5.0.2 on 2024-02-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_cartu_contity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartu',
            name='contity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
